# version string format -- This will be overwritten later anyway
version: "{branch}.{build}"

os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

install:
  - git submodule update --init --recursive

# Win32 and x64 are CMake-compatible solution platform names.
# This allows us to pass %PLATFORM% to CMake -A.
platform:
  - Win32
  - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

#Cmake will autodetect the compiler, but we set the arch
before_build:
  # zlib
  - |-
    curl -fsSL -o zlib.tar.gz https://github.com/madler/zlib/archive/v1.2.8.tar.gz
    7z x zlib.tar.gz -so | 7z x -si -ttar > nul
    move zlib-1.2.8 zlib
    cd zlib
    cmake -H. -BBuild -A%PLATFORM% -DCMAKE_INSTALL_PREFIX=%PREFIX%
    cmake --build ./Build --target install
    cd ..
  
  - |-
    curl -fsSL -o physfs.tar.bz2 https://icculus.org/physfs/downloads/physfs-3.0.1.tar.bz2
    7z x physfs.tar.bz2 -so | 7z x -si -ttar > nul
    move physfs-3.0.1 physfs
    cd physfs
    cmake -H. -BBuild -A%PLATFORM% -DCMAKE_INSTALL_PREFIX=%PREFIX% -DPHYSFS_BUILD_TEST=OFF
    cmake --build ./Build --target install
    cd ..
  
  - cmake -H. -BBuild -A%PLATFORM% -DCMAKE_PREFIX_PATH="%PREFIX%" -DCMAKE_BUILD_TYPE=%CONFIGURATION%

# build with MSBuild
build:
  project: Build\malefica.sln           # path to Visual Studio solution or project
  parallel: true                        # enable MSBuild parallel builds
  verbosity: normal                     # MSBuild verbosity level {quiet|minimal|normal|detailed}

test_script:
  - cd Build
  - ctest -V -C %CONFIGURATION%